URL_SERVICE = "https://767116a6-6c7a-48b0-938e-25e162a6ff62.serverhub.praktikum-services.ru"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
CREATE_USER_PATH = "/api/v1/users"
PRODUCTS_KITS_PATH = "/api/v1/products/kits"